### ISSUE TITLE
Support comment format

### ISSUE THREAD

**Issue by sonatard** [gqlgo/gqlfmt#1]
We will  support comment format after fix this issue https://github.com/vektah/gqlparser/issues/145 .

Currently `gqlfmt` delete comment lines.

**Comment by StevenACoffman** [comment]
@sonatard Hey, this is fixed now!
```
go get github.com/vektah/gqlparser/v2@v2.5.4
```

**Comment by sonatard** [comment]
@StevenACoffman Thanks!

I created new issue https://github.com/vektah/gqlparser/issues/262
